openapi: 3.0.0
info:
  title: Blog API
  description: API for managing blogs and comments
  version: 1.0.0
  tags:
    - name: blogs
      description: Blog operations
paths:
  /api/blog/posts:
    get:
      summary: Retrieve all blogs
      tags:
        - blogs
      responses:
        "200":
          description: A list of blogs
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Blog"